import React from 'react'
import { Icon } from './Icons'

const format = value => `${value.toLocaleString('ar-IQ')} د.ع`
export function ProductOptions({ product, onClose, onAdd }) {
  const [size, setSize] = React.useState('عادي')
  const [addons, setAddons] = React.useState([])
  const [quantity, setQuantity] = React.useState(1)
  const total = (product.price + (size === 'كبير' ? 1000 : 0) + addons.length * 500) * quantity
  const toggle = name => setAddons(list => list.includes(name) ? list.filter(v => v !== name) : [...list, name])
  return <Dialog onClose={onClose} className="options-dialog"><div className="options-hero"><button className="close" onClick={onClose}><Icon name="x"/></button><div className={`options-product shade-${product.id % 5}`}>☕</div><div><p>{product.category}</p><h2>{product.name}</h2><span>{format(product.price)}</span></div></div><section><h3>الحجم</h3><div className="choice-row">{[['صغير',-500],['عادي',0],['كبير',1000]].map(([label, add]) => <button key={label} onClick={() => setSize(label)} className={size === label ? 'active' : ''}>{label}<small>{add ? `${add > 0 ? '+' : ''}${format(add)}` : 'السعر الأساسي'}</small></button>)}</div></section><section><h3>الإضافات</h3><div className="addon-list">{['شوت إضافي','فانيلا','كراميل','حليب خالي اللاكتوز'].map(name => <label key={name}><input type="checkbox" checked={addons.includes(name)} onChange={() => toggle(name)}/><span>{name}</span><b>+٥٠٠ د.ع</b></label>)}</div></section><section><h3>ملاحظات خاصة</h3><textarea placeholder="مثال: بدون سكر، ثلج قليل" /></section><div className="dialog-footer"><div className="quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Icon name="minus" size={16}/></button><b>{quantity}</b><button onClick={() => setQuantity(quantity + 1)}><Icon name="plus" size={16}/></button></div><button className="primary-action" onClick={() => onAdd({ ...product, quantity, options: [size, ...addons].join(' • ') })}>إضافة للطلب <b>{format(total)}</b></button></div></Dialog>
}

export function OrderType({ onClose, onChoose }) { const types = [['داخل الكوفي','table'],['استلام من الكوفي','coffee'],['استلام من السيارة','card'],['توصيل','arrow']]; return <Dialog onClose={onClose} className="type-dialog"><button className="close" onClick={onClose}><Icon name="x"/></button><h2>كيف يرغب العميل باستلام الطلب؟</h2><p>اختر نوع الطلب للمتابعة إلى الدفع</p><div className="type-grid">{types.map(([label, icon]) => <button onClick={() => onChoose(label)} key={label}><span><Icon name={icon} size={29}/></span><b>{label}</b><Icon name="arrow" size={18}/></button>)}</div></Dialog> }

export function TableSelection({ onClose, onChoose }) { const statuses = ['free','busy','free','waiting','reserved','free','busy','free','free','waiting','free','free']; return <Dialog onClose={onClose} className="tables-dialog"><button className="close" onClick={onClose}><Icon name="x"/></button><h2>اختر الطاولة</h2><p>الطاولات المتاحة يمكن ربطها بالطلب مباشرة</p><div className="table-grid">{statuses.map((status, i) => <button disabled={status !== 'free'} className={status} onClick={() => onChoose(i + 1)} key={i}><Icon name="table" size={27}/><b>{i + 1}</b><small>{status === 'free' ? 'فارغة' : status === 'busy' ? 'مشغولة' : status === 'waiting' ? 'بانتظار الحساب' : 'محجوزة'}</small></button>)}</div><div className="legend"><span className="free">فارغة</span><span className="busy">مشغولة</span><span className="waiting">بانتظار الحساب</span><span className="reserved">محجوزة</span></div></Dialog> }

export function Payment({ total, onClose, onSuccess }) { const [method,setMethod] = React.useState(''); const [received,setReceived] = React.useState(''); const amount = Number(received.replace(/,/g,'')) || 0; const change = Math.max(0, amount-total); return <Dialog onClose={onClose} className="payment-dialog"><button className="close" onClick={onClose}><Icon name="x"/></button><p>الإجمالي المطلوب</p><h2>{format(total)}</h2><div className="payment-methods"><button className={method === 'نقدي' ? 'chosen' : ''} onClick={() => setMethod('نقدي')}><Icon name="coffee" size={28}/><b>نقدي</b></button><button className={method === 'إلكتروني' ? 'chosen' : ''} onClick={() => setMethod('إلكتروني')}><Icon name="card" size={28}/><b>إلكتروني</b></button></div>{method === 'نقدي' && <div className="cash-calc"><label>المبلغ المستلم<input autoFocus value={received} onChange={e=>setReceived(e.target.value)} inputMode="numeric" placeholder="0 د.ع"/></label><div className="quick-cash">{[20000,25000,50000].map(value => <button onClick={() => setReceived(String(value))} key={value}>{format(value)}</button>)}</div><div className="change"><span>الباقي للعميل</span><b>{format(change)}</b></div></div>}{method === 'إلكتروني' && <div className="electronic-note">سيتم تسجيل الدفع الإلكتروني فقط. لا يوجد تكامل دفع فعلي في هذه النسخة.</div>}<button className="primary-action" disabled={!method || (method === 'نقدي' && amount < total)} onClick={onSuccess}>إتمام الدفع <Icon name="check" size={19}/></button></Dialog> }

export function Success({ total, onClose, onReceipt }) { return <Dialog onClose={onClose} className="success-dialog"><div className="success-icon"><Icon name="check" size={34}/></div><h2>تم تسجيل الطلب بنجاح</h2><p>رقم الطلب <b>#1015</b></p><strong>{format(total)}</strong><div className="success-actions"><button onClick={onReceipt}>عرض الفاتورة</button><button onClick={() => window.print()}>طباعة الفاتورة</button><button className="primary-action" onClick={onClose}>طلب جديد</button></div></Dialog> }

export function OpenOrders({ onClose, onHistory }) { const orders=[['#1011','داخل الكوفي • طاولة 7','٨,٥٠٠ د.ع','قيد التحضير'],['#1010','استلام من الكوفي','٥,٠٠٠ د.ع','معلق'],['#1009','داخل الكوفي • طاولة 2','١٢,٠٠٠ د.ع','مكتمل']]; return <Dialog onClose={onClose} className="open-dialog"><button className="close" onClick={onClose}><Icon name="x"/></button><h2>الطلبات المفتوحة</h2><div className="order-filters"><button className="active">الطلبات المفتوحة</button><button>المعلقة</button><button>المكتملة حديثًا</button></div>{orders.map(o=><button className="open-order" onClick={o[3] === 'مكتمل' ? onHistory : undefined} key={o[0]}><span><b>{o[0]}</b><small>١٠:١٤ ص • ٣ منتجات</small></span><span>{o[1]}<b>{o[2]}</b></span><em className={o[3] === 'معلق' ? 'held' : ''}>{o[3]}</em></button>)}</Dialog> }

export function History({ onClose }) { return <Dialog onClose={onClose} className="history-dialog"><button className="close" onClick={onClose}><Icon name="x"/></button><p>فاتورة مكتملة <b>#1009</b></p><h2>سجل التعديلات</h2><div className="timeline"><div><i/> <b>١٠:٣٠</b><span>تم إنشاء الطلب بواسطة أحمد</span></div><div><i/> <b>١٠:٣٢</b><span>تم الدفع نقدًا</span></div><div><i/> <b>١٠:٤٠</b><span>تم إرجاع منتج — السبب: طلب غير صحيح</span></div><div><i/> <b>١٠:٤٣</b><span>تمت إضافة منتج للطلب</span></div></div><div className="sensitive-actions"><button>إضافة للطلب</button><button>إرجاع منتج</button><button>إعادة طباعة الفاتورة</button></div></Dialog> }

function Dialog({ children, onClose, className = '' }) { return <div className="overlay" role="dialog" aria-modal="true" onMouseDown={e => e.target === e.currentTarget && onClose()}><div className={`dialog ${className}`}>{children}</div></div> }
