import React, { useEffect, useMemo, useState } from 'react'
import { formatMoney, formatDateTime } from '../utils.js'
import { readCentralExpensesForReports, readLocalExpenses } from '../services/posCentralSync.js'
import { getReportSalesForPeriod, readLocalSales } from '../services/reportSales.js'
import { calculateEmployeeExpenseReport, calculateFinancialReport, calculateCashboxBalance, hasActualCash, normalizeFundingSource, toMoneyNumber } from '../services/financialCenter.js'
import { getEffectiveSettlement } from '../services/financialCenter.js'
import { buildCashboxReportData } from '../services/financialCenter.js'
import { verifySystemAdminCode } from '../services/systemAdminCode.js'
import { BUILD_SHA } from '../services/versionUpdate.js'

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Baghdad' }).format(new Date())
const safeMoney = value => formatMoney(toMoneyNumber(value, 0))
const actualCashMissingLabel = row => row?.day?.status === 'closed' ? 'غير مسجل في هذا التقرير القديم' : 'بانتظار إدخال الكاش الفعلي'
const optionalMoney = (value, missingLabel = 'بانتظار إدخال الكاش الفعلي') => hasActualCash(value) ? safeMoney(value) : missingLabel

export default function FinancialCenter({ transactions = [], centralSales = [], cashboxSales = [], operationalDays = [], operationalDay = null, settlements = [], settlementCorrections = [], onSaveTransaction, onUpdateTransaction, onVoidTransaction, onSaveCashCount, onSaveSettlementCorrection, onNavigate, adminDiagnostic = false }) {
  const [from, setFrom] = useState(today())
  const [to, setTo] = useState(today())
  const [txType, setTxType] = useState('deposit')
  const [txAmount, setTxAmount] = useState('')
  const [txReason, setTxReason] = useState('')
  const [fundingSource, setFundingSource] = useState('cashbox')
  const [editingTransactionId, setEditingTransactionId] = useState(null)
  const [countAmount, setCountAmount] = useState('')
  const [cashboxMovementsOpen, setCashboxMovementsOpen] = useState(false)
  const [correctionTarget, setCorrectionTarget] = useState(null)
  const [correctionStage, setCorrectionStage] = useState(null)
  const [systemCode, setSystemCode] = useState('')
  const [correctedActualCash, setCorrectedActualCash] = useState('')
  const [correctionReason, setCorrectionReason] = useState('')
  const [correctionNotes, setCorrectionNotes] = useState('')
  const [correctionError, setCorrectionError] = useState('')
  const [deployMeta, setDeployMeta] = useState(null)
  useEffect(() => {
    const dirty = Boolean(editingTransactionId || txAmount || txReason || countAmount || systemCode || correctedActualCash || correctionReason || correctionNotes)
    window.dispatchEvent(new CustomEvent('pos101-form-dirty', { detail: { dirty } }))
    return () => window.dispatchEvent(new CustomEvent('pos101-form-dirty', { detail: { dirty: false } }))
  }, [editingTransactionId, txAmount, txReason, countAmount, systemCode, correctedActualCash, correctionReason, correctionNotes])
  const localSales = useMemo(() => readLocalSales(), [])
  const sales = useMemo(() => getReportSalesForPeriod({ localSales, centralSales, operationalDays, from, to, currentOperationalDay: operationalDay }), [localSales, centralSales, operationalDays, from, to, operationalDay])
  const [expenses, setExpenses] = useState(() => readLocalExpenses())
  useEffect(() => {
    let active = true
    void readCentralExpensesForReports({ includeAllLocal: true, persistCache: false, dispatchUpdate: false })
      .then(result => { if (active && Array.isArray(result?.expenses)) setExpenses(result.expenses) })
      .catch(() => {})
    return () => { active = false }
  }, [])
  useEffect(() => {
    if (!adminDiagnostic) return undefined
    let active = true
    fetch(`${import.meta.env.BASE_URL}deploy-meta.json?v=${Date.now()}`, { cache: 'no-store' }).then(response => response.ok ? response.json() : null).then(meta => { if (active) setDeployMeta(meta) }).catch(() => {})
    return () => { active = false }
  }, [adminDiagnostic])
  const report = useMemo(() => calculateFinancialReport({ sales, expenses, transactions, from, to }), [sales, expenses, transactions, from, to])
  const employees = useMemo(() => calculateEmployeeExpenseReport(expenses, transactions, { from, to }), [expenses, transactions, from, to])
  const balance = calculateCashboxBalance(transactions)
  const closedSettlements = useMemo(() => settlements.filter(row => row.businessDate >= from && row.businessDate <= to).map(settlement => ({ settlement, effective: getEffectiveSettlement(settlement, settlementCorrections.filter(row => row.settlementId === settlement.id)) })), [settlements, settlementCorrections, from, to])
  const cashboxReportData = useMemo(() => buildCashboxReportData({ from, to, operationalDays, settlements, settlementCorrections, sales: cashboxSales, expenses, transactions }), [from, to, operationalDays, settlements, settlementCorrections, cashboxSales, expenses, transactions])
  const cashboxDebugEnabled = new URLSearchParams(window.location.search).has('cashbox-debug')
  const cashboxRows = cashboxReportData.rows
  const currentCashboxRow = cashboxReportData.selected || cashboxRows.find(row => String(row.day.id) === String(operationalDay?.id)) || cashboxRows[0] || null
  const displayedReport = cashboxReportData.summary || report
  const salesSourceUnavailable = cashboxSales.length === 0
  const cardValue = (label, value) => {
    if (salesSourceUnavailable && ['إجمالي المبيعات', 'نقدي', 'إلكتروني'].includes(label)) return 'غير متوفر'
    if ((!currentCashboxRow || !currentCashboxRow.openingCashKnown) && ['رصيد الصندوق', 'المتوقع'].includes(label)) return 'غير متوفر'
    return formatMoney(value)
  }
  const openCorrectionGate = settlement => { setCorrectionTarget(settlement); setCorrectionStage('code'); setSystemCode(''); setCorrectionError('') }
  const verifyCorrectionGate = event => { event.preventDefault(); if (!verifySystemAdminCode(systemCode)) { setCorrectionError('رمز النظام غير صحيح.'); return }; setCorrectionStage('form'); setCorrectionError('') }
  const submitCorrection = async event => {
    event.preventDefault()
    if (!correctionReason.trim() || correctedActualCash === '') { setCorrectionError('المبلغ الصحيح وسبب التصحيح مطلوبان.'); return }
    try {
      await onSaveSettlementCorrection?.({ settlementId: correctionTarget.id, correctedActualCash, reason: correctionReason, notes: correctionNotes, systemCode })
      setCorrectionStage(null); setCorrectionTarget(null); setCorrectionReason(''); setCorrectionNotes(''); setCorrectedActualCash(''); setCorrectionError('')
    } catch (error) { setCorrectionError(error?.message || 'تعذر حفظ التصحيح.') }
  }
  const saveTransaction = async event => { event.preventDefault(); const amount = Number(txAmount); if (!Number.isFinite(amount) || amount <= 0) return; const payload = { id: editingTransactionId || `${txType}-${from}-${amount}-${txReason.trim()}`, type: txType, amount, businessDate: from, reason: txReason.trim(), status: 'active', ...(txType === 'withdrawal' ? { fundingSource } : {}) }; if (editingTransactionId) await onUpdateTransaction?.(payload); else await onSaveTransaction?.(payload); setTxAmount(''); setTxReason(''); setFundingSource('cashbox'); setEditingTransactionId(null) }
  const beginEditTransaction = row => { setEditingTransactionId(row.id); setTxType(row.type); setTxAmount(String(row.amount)); setTxReason(row.reason || row.description || row.notes || ''); setFundingSource(normalizeFundingSource(row.fundingSource)); setFrom(row.businessDate || from) }
  const saveCount = async event => { event.preventDefault(); if (countAmount === '') return; await onSaveCashCount?.({ businessDate: from, systemBalance: balance, actualBalance: Number(countAmount), reason: 'جرد الصندوق' }); setCountAmount('') }
  return <section className="financial-center" dir="rtl">
    <div className="financial-heading"><div><button className="back-link" type="button" onClick={() => onNavigate?.('dashboard')}>← الرئيسية</button><h1>الصندوق</h1><p>المصدر المركزي للحركات هو Firebase، مع اعتماد businessDate.</p></div><div className="report-print-actions"><button className="primary-action" type="button" onClick={() => window.print()}>طباعة A4 / PDF</button><button className="outline-btn" type="button" onClick={() => window.print()}>طباعة حرارية 80mm</button></div></div>
    <div className="financial-filters"><label>من تاريخ<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>إلى تاريخ<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><button type="button" onClick={() => { setFrom(today()); setTo(today()) }}>اليوم</button><button type="button" onClick={() => { const d = new Date(); d.setDate(d.getDate() - 6); setFrom(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Baghdad' }).format(d)); setTo(today()) }}>آخر 7 أيام</button></div>
    {salesSourceUnavailable && <p role="alert">تعذر تحميل بيانات الصندوق</p>}
    <div className="financial-cards">{[['رصيد الصندوق', displayedReport.openingCashBalance ?? balance], ['إجمالي المبيعات', displayedReport.sales], ['نقدي', displayedReport.cashSales], ['إلكتروني', displayedReport.electronicSales], ['إجمالي المصاريف', displayedReport.cashboxExpenses ?? displayedReport.expenses ?? displayedReport.expensesTotal], ['مصاريف من الصندوق', displayedReport.cashboxExpenses], ['مصاريف من الإدارة', displayedReport.managementExpenses], ['سحوبات من الصندوق', displayedReport.cashboxWithdrawals], ['سحوبات من الإدارة', displayedReport.managementWithdrawals], ['إجمالي السحوبات', displayedReport.withdrawals], ['المتوقع', displayedReport.expectedCash ?? displayedReport.expectedClosingCash]].map(([label, value]) => <article key={label} className="financial-card"><span>{label}</span><strong>{cardValue(label, value)}</strong></article>)}</div>
    {currentCashboxRow && <section className="settings-card end-day-report-summary" aria-label="ملخص نهاية اليوم"><h2>ملخص نهاية اليوم</h2><div className="financial-table-wrap"><table className="financial-table"><tbody>
      <tr><td>الرصيد الافتتاحي</td><td>{currentCashboxRow.openingCashKnown ? safeMoney(currentCashboxRow.openingCashBalance) : 'غير متوفر'}</td></tr>
      <tr><td>مبيعات الكاش</td><td>{safeMoney(currentCashboxRow.cashSales)}</td></tr>
      <tr><td>المصاريف</td><td>{safeMoney(currentCashboxRow.expenses)}</td></tr>
      <tr><td>السحوبات</td><td>{safeMoney(currentCashboxRow.withdrawals)}</td></tr>
      <tr className="summary-highlight"><td>الرصيد المتوقع بالصندوق</td><td>{currentCashboxRow.openingCashKnown ? safeMoney(currentCashboxRow.expectedClosingCash) : 'غير متوفر'}</td></tr>
      <tr><td>الكاش الفعلي</td><td>{optionalMoney(currentCashboxRow.actualCash, actualCashMissingLabel(currentCashboxRow))}</td></tr>
      <tr><td>الفرق</td><td>{currentCashboxRow.difference == null ? actualCashMissingLabel(currentCashboxRow) : `${safeMoney(currentCashboxRow.difference)} ${currentCashboxRow.status === 'matched' ? 'مطابق' : currentCashboxRow.status === 'short' ? 'نقص' : 'زيادة'}`}</td></tr>
      <tr><td>صافي حركة الصندوق بعد خصم الرصيد الافتتاحي</td><td>{optionalMoney(currentCashboxRow.netDrawerMovement, actualCashMissingLabel(currentCashboxRow))}</td></tr>
      <tr><td>صافي مبيعات اليوم النقدية</td><td>{optionalMoney(currentCashboxRow.netCashSalesFromDrawer, actualCashMissingLabel(currentCashboxRow))}</td></tr>
      <tr><td>فرق المبيعات النقدية</td><td>{currentCashboxRow.cashSalesDifference == null ? actualCashMissingLabel(currentCashboxRow) : `${safeMoney(currentCashboxRow.cashSalesDifference)} ${currentCashboxRow.cashSalesDifferenceStatus === 'matched' ? 'مطابق' : currentCashboxRow.cashSalesDifferenceStatus === 'short' ? 'نقص' : 'زيادة'}`}</td></tr>
    </tbody></table></div></section>}
    <div className="financial-grid"><section className={`settings-card collapsible-card${cashboxMovementsOpen ? ' is-open' : ''}`}><div className="collapsible-card-heading"><h2>حركة الصندوق</h2><button type="button" className="collapsible-toggle" aria-expanded={cashboxMovementsOpen} aria-controls="cashbox-movements-content" onClick={() => setCashboxMovementsOpen(open => !open)}><span>{cashboxMovementsOpen ? 'إخفاء' : 'عرض'}</span><span className="collapsible-chevron" aria-hidden="true">{cashboxMovementsOpen ? '⌃' : '⌄'}</span></button></div>{cashboxMovementsOpen && <div id="cashbox-movements-content"><form className="financial-form" onSubmit={saveTransaction}><select value={txType} onChange={e => setTxType(e.target.value)}><option value="deposit">إيداع</option><option value="withdrawal">سحب</option><option value="adjustment">تصحيح</option><option value="return">إرجاع</option></select>{txType === 'withdrawal' && <label>مصدر السحب<select value={fundingSource} onChange={e => setFundingSource(e.target.value)}><option value="cashbox">من الصندوق</option><option value="management">من الإدارة</option></select></label>}<input type="number" min="1" value={txAmount} onChange={e => setTxAmount(e.target.value)} placeholder="المبلغ" /><input value={txReason} onChange={e => setTxReason(e.target.value)} placeholder="السبب" /><button className="primary-action">{editingTransactionId ? 'حفظ التعديل' : 'حفظ'}</button>{editingTransactionId && <button type="button" className="outline-btn" onClick={() => { setEditingTransactionId(null); setTxAmount(''); setTxReason(''); setFundingSource('cashbox') }}>إلغاء التعديل</button>}</form><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>التاريخ</th><th>النوع</th><th>المصدر</th><th>المبلغ</th><th>السبب</th><th /></tr></thead><tbody>{transactions.slice().reverse().map(row => <tr key={row.id}><td>{row.businessDate}</td><td>{row.type}</td><td>{row.type === 'withdrawal' ? (normalizeFundingSource(row.fundingSource) === 'management' ? 'من الإدارة' : 'من الصندوق') : '—'}</td><td>{formatMoney(row.amount)}</td><td>{row.reason || '—'}</td><td>{row.status !== 'voided' && <><button type="button" onClick={() => beginEditTransaction(row)}>تعديل</button><button type="button" onClick={() => onVoidTransaction?.(row)}>إلغاء</button></>}</td></tr>)}</tbody></table></div></div>}</section></div>
    <section className="settings-card"><h2>جرد الصندوق</h2><form className="financial-form" onSubmit={saveCount}><span>الرصيد النظامي: <b>{formatMoney(balance)}</b></span><input type="number" min="0" value={countAmount} onChange={e => setCountAmount(e.target.value)} placeholder="النقد الفعلي" /><button className="primary-action">حفظ الجرد</button>{countAmount !== '' && <span>الفرق: <b>{formatMoney(Number(countAmount) - balance)}</b></span>}</form></section><section className="settings-card"><h2>مصاريف الموظفين</h2><div className="employee-cards">{employees.map(row => <article className="employee-card" key={row.employeeId}><h3>{row.name}</h3><strong>{formatMoney(row.total)}</strong><span>{row.operations} عملية · سحب {formatMoney(row.withdrawals)}</span><button type="button" onClick={() => window.print()}>طباعة تقرير</button></article>)}</div></section>
    <section className="settings-card"><h2>التفصيل اليومي</h2><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>businessDate</th><th>المبيعات</th><th>نقدي</th><th>إلكتروني</th><th>المصاريف</th><th>السحوبات</th><th>صافي النقد / المتوقع</th><th>الطلبات</th></tr></thead><tbody>{cashboxReportData.dailyRows.map(row => <tr key={row.businessDate}><td>{row.businessDate}{row.fallbackFromBusinessDate && <small> محسوب من businessDate لعدم توفر سجل اليوم التشغيلي</small>}</td><td>{formatMoney(row.sales)}</td><td>{formatMoney(row.cash)}</td><td>{formatMoney(row.electronic)}</td><td>{formatMoney(row.expenses)}</td><td>{formatMoney(row.withdrawals)}</td><td>{formatMoney(row.net)}</td><td>{row.orders}</td></tr>)}{!cashboxReportData.dailyRows.length && <tr><td colSpan="8">لا توجد بيانات ضمن الفترة.</td></tr>}</tbody></table></div></section>
    <section className="settings-card settlement-history-card"><h2>تقرير الصندوق</h2><p>المصدر المركزي: Firebase · هوية اليوم: businessDate مع operationalDayId عند توفره</p><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>التاريخ / الفتح / الإغلاق</th><th>الرصيد الافتتاحي</th><th>مبيعات الكاش</th><th>المصاريف</th><th>السحوبات</th><th>المتوقع</th><th>الفعلي</th><th>الفرق</th><th>صافي الحركة بعد الافتتاح</th><th>صافي المبيعات النقدية</th><th>فرق المبيعات</th><th>الحالة</th></tr></thead><tbody>{cashboxRows.map(row => <tr key={row.day.id}><td><b>{row.day.businessDate}</b><br /><small>{row.day.fallbackFromBusinessDate ? 'محسوب من businessDate · سجل اليوم التشغيلي غير مرتبط' : `${formatDateTime(row.day.startedAt)} → ${row.day.endedAt ? formatDateTime(row.day.endedAt) : 'مفتوح'} · ID: ${row.day.id}`}</small></td><td>{row.openingCashKnown ? safeMoney(row.openingCashBalance) : 'غير متوفر'}</td><td>{safeMoney(row.cashSales)}</td><td>{safeMoney(row.expenses)}</td><td>{safeMoney(row.withdrawals)}</td><td>{row.openingCashKnown ? safeMoney(row.expectedClosingCash) : 'غير متوفر'}</td><td>{row.hasSettlement ? optionalMoney(row.rolloverCash, actualCashMissingLabel(row)) : actualCashMissingLabel(row)}</td><td>{row.difference == null ? actualCashMissingLabel(row) : safeMoney(row.difference)}</td><td>{optionalMoney(row.netDrawerMovement, actualCashMissingLabel(row))}</td><td>{optionalMoney(row.netCashSalesFromDrawer, actualCashMissingLabel(row))}</td><td>{row.cashSalesDifference == null ? actualCashMissingLabel(row) : safeMoney(row.cashSalesDifference)}</td><td>{row.hasSettlement ? row.status : row.day.fallbackFromBusinessDate ? 'محسوب من businessDate' : 'لا توجد تسوية محفوظة'}</td></tr>)}{!cashboxRows.length && <tr><td colSpan="12">لا توجد أيام تشغيلية ضمن الفترة.</td></tr>}</tbody></table></div></section>
    {adminDiagnostic && <details className="settings-card non-printable" data-testid="cashbox-live-meta"><summary>LIVE_BUILD_META</summary><pre>{`LIVE_BUNDLE=${deployMeta?.bundle || 'unknown'}\nBUILD_SHA=${BUILD_SHA}`}</pre></details>}
    {cashboxDebugEnabled && <pre data-testid="cashbox-state-debug">{JSON.stringify({ from, to, cashboxInputSalesCount: cashboxSales.length, operationalDaysCount: operationalDays.length, expensesCount: expenses.length, transactionsCount: transactions.length, settlementsCount: settlements.length, reportRowsCount: cashboxRows.length, dailyRowsCount: cashboxReportData.dailyRows.length, selectedBusinessDate: cashboxReportData.selected?.day?.businessDate || null, selectedSales: cashboxReportData.selected?.sales || null, selectedCash: cashboxReportData.selected?.cashSales || null, selectedElectronic: cashboxReportData.selected?.electronicSales || null, selectedOpening: cashboxReportData.selected?.openingCashBalance ?? null, selectedExpected: cashboxReportData.selected?.expectedClosingCash ?? null }, null, 2)}</pre>}
    {adminDiagnostic && currentCashboxRow && <details className="settings-card non-printable" data-testid="cashbox-report-diagnostic"><summary>CASHBOX_VISIBLE_DIAGNOSTIC</summary><pre>{`CASHBOX_DATASET_DEBUG:\nbundle=${deployMeta?.bundle || 'unknown'}\ncommit=${BUILD_SHA}\nbusinessDate=${currentCashboxRow.day.businessDate}\nsalesSource=pos101_sales\nmatchedSalesCount=${currentCashboxRow.salesRecordsMatched}\ntotalSales=${currentCashboxRow.sales}\ncashSales=${currentCashboxRow.salesCashTotal}\nelectronicSales=${currentCashboxRow.salesElectronicTotal}\nopeningSource=${currentCashboxRow.day.openingSource || (currentCashboxRow.day.fallbackFromBusinessDate ? 'businessDateFallback' : 'operationalDay')}\nopeningCashBalance=${currentCashboxRow.openingCashBalance ?? 'unavailable'}\nexpectedCash=${currentCashboxRow.expectedClosingCash ?? 'unavailable'}\nusesSharedDataset=YES`}</pre></details>}
    <section className="settings-card settlement-history-card"><h2>تسويات الأيام المغلقة</h2><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>التاريخ</th><th>المبلغ المتوقع</th><th>المبلغ الفعلي</th><th>الفرق</th><th>الحالة</th><th /></tr></thead><tbody>{closedSettlements.map(({ settlement, effective }) => <tr key={settlement.id}><td>{settlement.businessDate}</td><td>{formatMoney(settlement.expectedCash)}</td><td><b>{formatMoney(effective.effectiveActualCash)}</b>{effective.correction && <small className="settlement-corrected-label">تم التصحيح</small>}</td><td>{formatMoney(effective.effectiveDifference)}</td><td>{effective.effectiveStatus}</td><td><button type="button" onClick={() => openCorrectionGate(settlement)}>تصحيح مبلغ الإغلاق</button><details><summary>التفاصيل الأصلية</summary><small>المبلغ الأصلي المدخل عند الإغلاق: {formatMoney(settlement.actualCash)} · الفرق الأصلي: {formatMoney(settlement.difference)}{effective.correction ? ` · سبب التصحيح: ${effective.correction.reason}` : ''}</small></details></td></tr>)}{!closedSettlements.length && <tr><td colSpan="6">لا توجد تسويات مغلقة ضمن الفترة.</td></tr>}</tbody></table></div></section>
    {correctionStage && correctionTarget && <div className="overlay"><div className="dialog settlement-correction-dialog" dir="rtl"><button className="close" type="button" onClick={() => setCorrectionStage(null)}>×</button>{correctionStage === 'code' ? <><h2>تصحيح مبلغ الإغلاق</h2><p>يتطلب هذا الإجراء رمز النظام.</p><form onSubmit={verifyCorrectionGate}><label>رمز النظام<input autoFocus type="password" inputMode="numeric" value={systemCode} onChange={event => setSystemCode(event.target.value.replace(/\D/g, '').slice(0, 4))} /></label>{correctionError && <p className="financial-pin-error" role="alert">{correctionError}</p>}<div className="dialog-actions"><button type="button" className="secondary-action" onClick={() => setCorrectionStage(null)}>إلغاء</button><button className="primary-action" disabled={systemCode.length !== 4}>متابعة</button></div></form></> : <><h2>تصحيح مبلغ الإغلاق</h2><label>المبلغ المتوقع<input readOnly value={formatMoney(correctionTarget.expectedCash)} /></label><label>المبلغ المدخل سابقاً<input readOnly value={formatMoney(correctionTarget.actualCash)} /></label><label>المبلغ الفعلي الصحيح<input autoFocus type="number" min="0" value={correctedActualCash} onChange={event => setCorrectedActualCash(event.target.value)} /></label><label>سبب التصحيح<input required value={correctionReason} onChange={event => setCorrectionReason(event.target.value)} /></label><label>ملاحظات<textarea value={correctionNotes} onChange={event => setCorrectionNotes(event.target.value)} /></label>{correctionError && <p className="financial-pin-error" role="alert">{correctionError}</p>}<div className="dialog-actions"><button type="button" className="secondary-action" onClick={() => setCorrectionStage(null)}>إلغاء</button><button className="primary-action" type="button" onClick={submitCorrection}>حفظ التصحيح</button></div></>}</div></div>}
  </section>
}
