import React, { useEffect, useMemo, useState } from 'react'
import { formatMoney, formatDateTime } from '../utils.js'
import { readCentralExpensesForReports, readLocalExpenses } from '../services/posCentralSync.js'
import { getReportSalesForPeriod, readLocalSales } from '../services/reportSales.js'
import { buildCashboxReportRows, calculateEmployeeExpenseReport, calculateFinancialReport, calculateCashboxBalance, normalizeFundingSource } from '../services/financialCenter.js'
import { getEffectiveSettlement } from '../services/financialCenter.js'
import { verifySystemAdminCode } from '../services/systemAdminCode.js'

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Baghdad' }).format(new Date())

export default function FinancialCenter({ transactions = [], centralSales = [], operationalDays = [], operationalDay = null, settlements = [], settlementCorrections = [], onSaveTransaction, onUpdateTransaction, onVoidTransaction, onSaveCashCount, onSaveSettlementCorrection, onNavigate }) {
  const [from, setFrom] = useState(today())
  const [to, setTo] = useState(today())
  const [txType, setTxType] = useState('deposit')
  const [txAmount, setTxAmount] = useState('')
  const [txReason, setTxReason] = useState('')
  const [fundingSource, setFundingSource] = useState('cashbox')
  const [editingTransactionId, setEditingTransactionId] = useState(null)
  const [countAmount, setCountAmount] = useState('')
  const [cashboxMovementsOpen, setCashboxMovementsOpen] = useState(false)
  const [correctionTarget, setCorrectionTarget] = useState(null)
  const [correctionStage, setCorrectionStage] = useState(null)
  const [systemCode, setSystemCode] = useState('')
  const [correctedActualCash, setCorrectedActualCash] = useState('')
  const [correctionReason, setCorrectionReason] = useState('')
  const [correctionNotes, setCorrectionNotes] = useState('')
  const [correctionError, setCorrectionError] = useState('')
  const localSales = useMemo(() => readLocalSales(), [])
  const sales = useMemo(() => getReportSalesForPeriod({ localSales, centralSales, operationalDays, from, to, currentOperationalDay: operationalDay }), [localSales, centralSales, operationalDays, from, to, operationalDay])
  const [expenses, setExpenses] = useState(() => readLocalExpenses())
  useEffect(() => {
    let active = true
    void readCentralExpensesForReports({ includeAllLocal: true, persistCache: false, dispatchUpdate: false })
      .then(result => { if (active && Array.isArray(result?.expenses)) setExpenses(result.expenses) })
      .catch(() => {})
    return () => { active = false }
  }, [])
  const report = useMemo(() => calculateFinancialReport({ sales, expenses, transactions, from, to }), [sales, expenses, transactions, from, to])
  const employees = useMemo(() => calculateEmployeeExpenseReport(expenses, transactions, { from, to }), [expenses, transactions, from, to])
  const balance = calculateCashboxBalance(transactions)
  const closedSettlements = useMemo(() => settlements.filter(row => row.businessDate >= from && row.businessDate <= to).map(settlement => ({ settlement, effective: getEffectiveSettlement(settlement, settlementCorrections.filter(row => row.settlementId === settlement.id)) })), [settlements, settlementCorrections, from, to])
  const cashboxRows = useMemo(() => buildCashboxReportRows({ operationalDays: operationalDays.filter(day => day.businessDate >= from && day.businessDate <= to), settlements, settlementCorrections, sales: centralSales, expenses, transactions }), [operationalDays, settlements, settlementCorrections, centralSales, expenses, transactions, from, to])
  const openCorrectionGate = settlement => { setCorrectionTarget(settlement); setCorrectionStage('code'); setSystemCode(''); setCorrectionError('') }
  const verifyCorrectionGate = event => { event.preventDefault(); if (!verifySystemAdminCode(systemCode)) { setCorrectionError('رمز النظام غير صحيح.'); return }; setCorrectionStage('form'); setCorrectionError('') }
  const submitCorrection = async event => {
    event.preventDefault()
    if (!correctionReason.trim() || correctedActualCash === '') { setCorrectionError('المبلغ الصحيح وسبب التصحيح مطلوبان.'); return }
    try {
      await onSaveSettlementCorrection?.({ settlementId: correctionTarget.id, correctedActualCash, reason: correctionReason, notes: correctionNotes, systemCode })
      setCorrectionStage(null); setCorrectionTarget(null); setCorrectionReason(''); setCorrectionNotes(''); setCorrectedActualCash(''); setCorrectionError('')
    } catch (error) { setCorrectionError(error?.message || 'تعذر حفظ التصحيح.') }
  }
  const saveTransaction = async event => { event.preventDefault(); const amount = Number(txAmount); if (!Number.isFinite(amount) || amount <= 0) return; const payload = { id: editingTransactionId || `${txType}-${from}-${amount}-${txReason.trim()}`, type: txType, amount, businessDate: from, reason: txReason.trim(), status: 'active', ...(txType === 'withdrawal' ? { fundingSource } : {}) }; if (editingTransactionId) await onUpdateTransaction?.(payload); else await onSaveTransaction?.(payload); setTxAmount(''); setTxReason(''); setFundingSource('cashbox'); setEditingTransactionId(null) }
  const beginEditTransaction = row => { setEditingTransactionId(row.id); setTxType(row.type); setTxAmount(String(row.amount)); setTxReason(row.reason || row.description || row.notes || ''); setFundingSource(normalizeFundingSource(row.fundingSource)); setFrom(row.businessDate || from) }
  const saveCount = async event => { event.preventDefault(); if (countAmount === '') return; await onSaveCashCount?.({ businessDate: from, systemBalance: balance, actualBalance: Number(countAmount), reason: 'جرد الصندوق' }); setCountAmount('') }
  return <section className="financial-center" dir="rtl">
    <div className="financial-heading"><div><button className="back-link" type="button" onClick={() => onNavigate?.('dashboard')}>← الرئيسية</button><h1>الصندوق</h1><p>المصدر المركزي للحركات هو Firebase، مع اعتماد businessDate.</p></div><div className="report-print-actions"><button className="primary-action" type="button" onClick={() => window.print()}>طباعة A4 / PDF</button><button className="outline-btn" type="button" onClick={() => window.print()}>طباعة حرارية 80mm</button></div></div>
    <div className="financial-filters"><label>من تاريخ<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>إلى تاريخ<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><button type="button" onClick={() => { setFrom(today()); setTo(today()) }}>اليوم</button><button type="button" onClick={() => { const d = new Date(); d.setDate(d.getDate() - 6); setFrom(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Baghdad' }).format(d)); setTo(today()) }}>آخر 7 أيام</button></div>
    <div className="financial-cards">{[['رصيد الصندوق', balance], ['إجمالي المبيعات', report.sales], ['نقدي', report.cashSales], ['إلكتروني', report.electronicSales], ['إجمالي المصاريف', report.expenses], ['مصاريف من الصندوق', report.cashboxExpenses], ['مصاريف من الإدارة', report.managementExpenses], ['سحوبات من الصندوق', report.cashboxWithdrawals], ['سحوبات من الإدارة', report.managementWithdrawals], ['إجمالي السحوبات', report.withdrawals], ['المتوقع', report.expectedCash]].map(([label, value]) => <article key={label} className="financial-card"><span>{label}</span><strong>{formatMoney(value)}</strong></article>)}</div>
    <div className="financial-grid"><section className={`settings-card collapsible-card${cashboxMovementsOpen ? ' is-open' : ''}`}><div className="collapsible-card-heading"><h2>حركة الصندوق</h2><button type="button" className="collapsible-toggle" aria-expanded={cashboxMovementsOpen} aria-controls="cashbox-movements-content" onClick={() => setCashboxMovementsOpen(open => !open)}><span>{cashboxMovementsOpen ? 'إخفاء' : 'عرض'}</span><span className="collapsible-chevron" aria-hidden="true">{cashboxMovementsOpen ? '⌃' : '⌄'}</span></button></div>{cashboxMovementsOpen && <div id="cashbox-movements-content"><form className="financial-form" onSubmit={saveTransaction}><select value={txType} onChange={e => setTxType(e.target.value)}><option value="deposit">إيداع</option><option value="withdrawal">سحب</option><option value="adjustment">تصحيح</option><option value="return">إرجاع</option></select>{txType === 'withdrawal' && <label>مصدر السحب<select value={fundingSource} onChange={e => setFundingSource(e.target.value)}><option value="cashbox">من الصندوق</option><option value="management">من الإدارة</option></select></label>}<input type="number" min="1" value={txAmount} onChange={e => setTxAmount(e.target.value)} placeholder="المبلغ" /><input value={txReason} onChange={e => setTxReason(e.target.value)} placeholder="السبب" /><button className="primary-action">{editingTransactionId ? 'حفظ التعديل' : 'حفظ'}</button>{editingTransactionId && <button type="button" className="outline-btn" onClick={() => { setEditingTransactionId(null); setTxAmount(''); setTxReason(''); setFundingSource('cashbox') }}>إلغاء التعديل</button>}</form><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>التاريخ</th><th>النوع</th><th>المصدر</th><th>المبلغ</th><th>السبب</th><th /></tr></thead><tbody>{transactions.slice().reverse().map(row => <tr key={row.id}><td>{row.businessDate}</td><td>{row.type}</td><td>{row.type === 'withdrawal' ? (normalizeFundingSource(row.fundingSource) === 'management' ? 'من الإدارة' : 'من الصندوق') : '—'}</td><td>{formatMoney(row.amount)}</td><td>{row.reason || '—'}</td><td>{row.status !== 'voided' && <><button type="button" onClick={() => beginEditTransaction(row)}>تعديل</button><button type="button" onClick={() => onVoidTransaction?.(row)}>إلغاء</button></>}</td></tr>)}</tbody></table></div></div>}</section></div>
    <section className="settings-card"><h2>جرد الصندوق</h2><form className="financial-form" onSubmit={saveCount}><span>الرصيد النظامي: <b>{formatMoney(balance)}</b></span><input type="number" min="0" value={countAmount} onChange={e => setCountAmount(e.target.value)} placeholder="النقد الفعلي" /><button className="primary-action">حفظ الجرد</button>{countAmount !== '' && <span>الفرق: <b>{formatMoney(Number(countAmount) - balance)}</b></span>}</form></section><section className="settings-card"><h2>مصاريف الموظفين</h2><div className="employee-cards">{employees.map(row => <article className="employee-card" key={row.employeeId}><h3>{row.name}</h3><strong>{formatMoney(row.total)}</strong><span>{row.operations} عملية · سحب {formatMoney(row.withdrawals)}</span><button type="button" onClick={() => window.print()}>طباعة تقرير</button></article>)}</div></section>
    <section className="settings-card"><h2>التفصيل اليومي</h2><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>businessDate</th><th>المبيعات</th><th>نقدي</th><th>إلكتروني</th><th>المصاريف</th><th>السحوبات</th><th>صافي النقد</th><th>الطلبات</th></tr></thead><tbody>{report.daily.map(row => <tr key={row.businessDate}><td>{row.businessDate}</td><td>{formatMoney(row.sales)}</td><td>{formatMoney(row.cash)}</td><td>{formatMoney(row.electronic)}</td><td>{formatMoney(row.expenses)}</td><td>{formatMoney(row.withdrawals)}</td><td>{formatMoney(row.net)}</td><td>{row.orders}</td></tr>)}</tbody></table></div></section>
    <section className="settings-card settlement-history-card"><h2>تقرير الصندوق</h2><p>المصدر المركزي: Firebase · هوية اليوم: operationalDayId</p><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>التاريخ / الفتح / الإغلاق</th><th>رصيد البداية</th><th>صافي حركة اليوم</th><th>المتوقع</th><th>الفعلي</th><th>الفرق</th><th>الحالة</th><th>المرحل لليوم التالي</th></tr></thead><tbody>{cashboxRows.map(row => <tr key={row.day.id}><td><b>{row.day.businessDate}</b><br /><small>{formatDateTime(row.day.startedAt)} → {row.day.endedAt ? formatDateTime(row.day.endedAt) : 'مفتوح'}<br />ID: {row.day.id}</small></td><td>{row.openingCashKnown ? formatMoney(row.openingCashBalance) : 'رصيد البداية غير محفوظ في هذا السجل القديم'}</td><td>{formatMoney(row.dailyCashMovement)}</td><td>{row.openingCashKnown ? formatMoney(row.expectedClosingCash) : 'غير متوفر'}</td><td>{row.hasSettlement ? formatMoney(row.rolloverCash) : 'غير متوفر'}</td><td>{row.difference == null ? 'غير متوفر' : formatMoney(row.difference)}</td><td>{row.hasSettlement ? row.status : 'لا توجد تسوية محفوظة'}</td><td>{row.rolloverCash == null ? 'غير متوفر' : formatMoney(row.rolloverCash)}</td></tr>)}{!cashboxRows.length && <tr><td colSpan="8">لا توجد أيام تشغيلية ضمن الفترة.</td></tr>}</tbody></table></div></section>
    <section className="settings-card settlement-history-card"><h2>تسويات الأيام المغلقة</h2><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>التاريخ</th><th>المبلغ المتوقع</th><th>المبلغ الفعلي</th><th>الفرق</th><th>الحالة</th><th /></tr></thead><tbody>{closedSettlements.map(({ settlement, effective }) => <tr key={settlement.id}><td>{settlement.businessDate}</td><td>{formatMoney(settlement.expectedCash)}</td><td><b>{formatMoney(effective.effectiveActualCash)}</b>{effective.correction && <small className="settlement-corrected-label">تم التصحيح</small>}</td><td>{formatMoney(effective.effectiveDifference)}</td><td>{effective.effectiveStatus}</td><td><button type="button" onClick={() => openCorrectionGate(settlement)}>تصحيح مبلغ الإغلاق</button><details><summary>التفاصيل الأصلية</summary><small>المبلغ الأصلي المدخل عند الإغلاق: {formatMoney(settlement.actualCash)} · الفرق الأصلي: {formatMoney(settlement.difference)}{effective.correction ? ` · سبب التصحيح: ${effective.correction.reason}` : ''}</small></details></td></tr>)}{!closedSettlements.length && <tr><td colSpan="6">لا توجد تسويات مغلقة ضمن الفترة.</td></tr>}</tbody></table></div></section>
    {correctionStage && correctionTarget && <div className="overlay"><div className="dialog settlement-correction-dialog" dir="rtl"><button className="close" type="button" onClick={() => setCorrectionStage(null)}>×</button>{correctionStage === 'code' ? <><h2>تصحيح مبلغ الإغلاق</h2><p>يتطلب هذا الإجراء رمز النظام.</p><form onSubmit={verifyCorrectionGate}><label>رمز النظام<input autoFocus type="password" inputMode="numeric" value={systemCode} onChange={event => setSystemCode(event.target.value.replace(/\D/g, '').slice(0, 4))} /></label>{correctionError && <p className="financial-pin-error" role="alert">{correctionError}</p>}<div className="dialog-actions"><button type="button" className="secondary-action" onClick={() => setCorrectionStage(null)}>إلغاء</button><button className="primary-action" disabled={systemCode.length !== 4}>متابعة</button></div></form></> : <><h2>تصحيح مبلغ الإغلاق</h2><label>المبلغ المتوقع<input readOnly value={formatMoney(correctionTarget.expectedCash)} /></label><label>المبلغ المدخل سابقاً<input readOnly value={formatMoney(correctionTarget.actualCash)} /></label><label>المبلغ الفعلي الصحيح<input autoFocus type="number" min="0" value={correctedActualCash} onChange={event => setCorrectedActualCash(event.target.value)} /></label><label>سبب التصحيح<input required value={correctionReason} onChange={event => setCorrectionReason(event.target.value)} /></label><label>ملاحظات<textarea value={correctionNotes} onChange={event => setCorrectionNotes(event.target.value)} /></label>{correctionError && <p className="financial-pin-error" role="alert">{correctionError}</p>}<div className="dialog-actions"><button type="button" className="secondary-action" onClick={() => setCorrectionStage(null)}>إلغاء</button><button className="primary-action" type="button" onClick={submitCorrection}>حفظ التصحيح</button></div></>}</div></div>}
  </section>
}
