import React, { useMemo, useState } from 'react'
import { formatMoney } from '../utils.js'
import { readLocalExpenses } from '../services/posCentralSync.js'
import { readLocalSales } from '../services/reportSales.js'
import { calculateEmployeeExpenseReport, calculateFinancialReport, calculateCashboxBalance } from '../services/financialCenter.js'

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Baghdad' }).format(new Date())

export default function FinancialCenter({ staff = [], transactions = [], onSaveStaff, onSaveTransaction, onVoidTransaction, onSaveCashCount, onNavigate }) {
  const [from, setFrom] = useState(today())
  const [to, setTo] = useState(today())
  const [name, setName] = useState('')
  const [code, setCode] = useState('')
  const [role, setRole] = useState('cashier')
  const [txType, setTxType] = useState('deposit')
  const [txAmount, setTxAmount] = useState('')
  const [txReason, setTxReason] = useState('')
  const [countAmount, setCountAmount] = useState('')
  const sales = useMemo(() => readLocalSales(), [])
  const expenses = useMemo(() => readLocalExpenses(), [])
  const report = useMemo(() => calculateFinancialReport({ sales, expenses, transactions, from, to }), [sales, expenses, transactions, from, to])
  const employees = useMemo(() => calculateEmployeeExpenseReport(expenses, transactions, { from, to }), [expenses, transactions, from, to])
  const balance = calculateCashboxBalance(transactions)
  const saveStaff = async event => { event.preventDefault(); if (!name.trim()) return; await onSaveStaff?.({ name: name.trim(), code: code.trim(), role, active: true }); setName(''); setCode('') }
  const saveTransaction = async event => { event.preventDefault(); const amount = Number(txAmount); if (!Number.isFinite(amount) || amount <= 0) return; await onSaveTransaction?.({ id: `${txType}-${from}-${amount}-${txReason.trim()}`, type: txType, amount, businessDate: from, reason: txReason.trim(), status: 'active' }); setTxAmount(''); setTxReason('') }
  const saveCount = async event => { event.preventDefault(); if (countAmount === '') return; await onSaveCashCount?.({ businessDate: from, systemBalance: balance, actualBalance: Number(countAmount), reason: 'جرد الصندوق' }); setCountAmount('') }
  return <section className="financial-center" dir="rtl">
    <div className="financial-heading"><div><button className="back-link" type="button" onClick={() => onNavigate?.('dashboard')}>← الرئيسية</button><h1>الصندوق</h1><p>المصدر المركزي للحركات هو Firebase، مع اعتماد businessDate.</p></div><button className="primary-action" type="button" onClick={() => window.print()}>طباعة A4 / PDF</button></div>
    <div className="financial-filters"><label>من تاريخ<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>إلى تاريخ<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><button type="button" onClick={() => { setFrom(today()); setTo(today()) }}>اليوم</button><button type="button" onClick={() => { const d = new Date(); d.setDate(d.getDate() - 6); setFrom(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Baghdad' }).format(d)); setTo(today()) }}>آخر 7 أيام</button></div>
    <div className="financial-cards">{[['رصيد الصندوق', balance], ['إجمالي المبيعات', report.sales], ['نقدي', report.cashSales], ['إلكتروني', report.electronicSales], ['المصاريف', report.expenses], ['السحوبات', report.withdrawals], ['المتوقع', report.expectedCash]].map(([label, value]) => <article key={label} className="financial-card"><span>{label}</span><strong>{formatMoney(value)}</strong></article>)}</div>
    <div className="financial-grid"><section className="settings-card"><h2>حركة صندوق</h2><form className="financial-form" onSubmit={saveTransaction}><select value={txType} onChange={e => setTxType(e.target.value)}><option value="deposit">إيداع</option><option value="withdrawal">سحب</option><option value="adjustment">تصحيح</option><option value="return">إرجاع</option></select><input type="number" min="1" value={txAmount} onChange={e => setTxAmount(e.target.value)} placeholder="المبلغ" /><input value={txReason} onChange={e => setTxReason(e.target.value)} placeholder="السبب" /><button className="primary-action">حفظ</button></form><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>التاريخ</th><th>النوع</th><th>المبلغ</th><th>السبب</th><th /></tr></thead><tbody>{transactions.slice().reverse().map(row => <tr key={row.id}><td>{row.businessDate}</td><td>{row.type}</td><td>{formatMoney(row.amount)}</td><td>{row.reason || '—'}</td><td>{row.status !== 'voided' && <button type="button" onClick={() => onVoidTransaction?.(row)}>إلغاء</button>}</td></tr>)}</tbody></table></div></section><section className="settings-card"><h2>إدارة الكاشير والموظفين</h2><form className="financial-form" onSubmit={saveStaff}><input value={name} onChange={e => setName(e.target.value)} placeholder="الاسم" /><input value={code} onChange={e => setCode(e.target.value)} placeholder="الكود" /><select value={role} onChange={e => setRole(e.target.value)}><option value="cashier">cashier</option><option value="employee">employee</option><option value="manager">manager</option></select><button className="primary-action">إضافة</button></form><div className="staff-list">{staff.map(row => <div className="staff-row" key={row.id}><b>{row.name}</b><span>{row.code || '—'} · {row.role}</span><small>{row.active ? 'فعال' : 'معطل'}</small></div>)}</div></section></div>
    <section className="settings-card"><h2>جرد الصندوق</h2><form className="financial-form" onSubmit={saveCount}><span>الرصيد النظامي: <b>{formatMoney(balance)}</b></span><input type="number" min="0" value={countAmount} onChange={e => setCountAmount(e.target.value)} placeholder="النقد الفعلي" /><button className="primary-action">حفظ الجرد</button>{countAmount !== '' && <span>الفرق: <b>{formatMoney(Number(countAmount) - balance)}</b></span>}</form></section><section className="settings-card"><h2>مصاريف الموظفين</h2><div className="employee-cards">{employees.map(row => <article className="employee-card" key={row.employeeId}><h3>{row.name}</h3><strong>{formatMoney(row.total)}</strong><span>{row.operations} عملية · سحب {formatMoney(row.withdrawals)}</span><button type="button" onClick={() => window.print()}>طباعة تقرير</button></article>)}</div></section>
    <section className="settings-card"><h2>التفصيل اليومي</h2><div className="financial-table-wrap"><table className="financial-table"><thead><tr><th>businessDate</th><th>المبيعات</th><th>نقدي</th><th>إلكتروني</th><th>المصاريف</th><th>السحوبات</th><th>صافي النقد</th><th>الطلبات</th></tr></thead><tbody>{report.daily.map(row => <tr key={row.businessDate}><td>{row.businessDate}</td><td>{formatMoney(row.sales)}</td><td>{formatMoney(row.cash)}</td><td>{formatMoney(row.electronic)}</td><td>{formatMoney(row.expenses)}</td><td>{formatMoney(row.withdrawals)}</td><td>{formatMoney(row.net)}</td><td>{row.orders}</td></tr>)}</tbody></table></div></section>
  </section>
}
