name = "pos101-kiosk-auth"
main = "src/index.js"
compatibility_date = "2026-10-06"

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://najf8.github.io,http://localhost:5174,http://127.0.0.1:5174"
FIREBASE_DATABASE_URL = "https://cmms-37512-default-rtdb.asia-southeast1.firebasedatabase.app"

[[kv_namespaces]]
binding = "KIOSK_RATE_LIMIT"
id = "589c3adfe4024255a5383ba7bbff1e94"
