import { useEffect, useMemo, useState } from 'react'
import Header from './components/Header'
import ProductGrid from './components/ProductGrid'
import OrderPanel from './components/OrderPanel'
import { ProductOptions, OrderType, TableSelection, Payment, QuickCash, DiscountDialog, OpenOrders, History, ReturnDialog, Receipt, CashierLogin, CashierMenu, ConfirmDialog, PrintMenu } from './components/Dialogs'
import { categories, products } from './data/menu'
import { Icon } from './components/Icons'
const blankOrder = index => ({ id:index, name:`طلب ${index}`, items:[], table:null, orderType:null, held:false, completed:false, adjustments:[] })
export const tablesEnabled = false
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback } catch { return fallback } }
const mockCashiers = [{ cashierId:'cashier-ali', name:'علي', pin:'1010', enabled:true }, { cashierId:'cashier-ahmed', name:'أحمد', pin:'2020', enabled:true }]
export default function App() {
  const [orders,setOrders] = useState(() => read('pos101.orders',[1,2,3,4].map(blankOrder)))
  const [nextNumber,setNextNumber] = useState(() => read('pos101.nextNumber',1015)), [active,setActive] = useState(0), [category,setCategory] = useState('الكل'), [query,setQuery] = useState(''), [modal,setModal] = useState(null), [selected,setSelected] = useState(null), [printSale,setPrintSale] = useState(null), [session,setSession] = useState(() => read('pos101.session',null)), [autoPrint,setAutoPrint] = useState(() => read('pos101.autoPrint',true))
  const activeOrder = orders[active] || orders[0]; const subtotal = activeOrder.items.reduce((s,i)=>s+i.price*i.quantity,0); const total = Math.max(0, subtotal-(activeOrder.discount?.value||0))
  const visibleProducts = useMemo(() => products.filter(p=>(category==='الكل'||p.category===category)&&`${p.name} ${p.english}`.toLowerCase().includes(query.toLowerCase())),[category,query])
  useEffect(()=>localStorage.setItem('pos101.orders',JSON.stringify(orders)),[orders]); useEffect(()=>localStorage.setItem('pos101.nextNumber',nextNumber),[nextNumber])
  useEffect(()=>localStorage.setItem('pos101.session',JSON.stringify(session)),[session]); useEffect(()=>localStorage.setItem('pos101.autoPrint',JSON.stringify(autoPrint)),[autoPrint])
  useEffect(()=>{ const key=e=>{ if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return; if(e.key==='Escape'){setModal(null);return} if(!session)return; if(e.key==='F7'){e.preventDefault();activeOrder.items.length?setModal('quickCash'):window.alert('أضف منتجًا أولًا قبل الدفع السريع')} if(e.key==='F8'){e.preventDefault();activeOrder.items.length&&setModal('payment-electronic')} if(e.key==='F9'){e.preventDefault();hold()} if(e.key==='F10'){e.preventDefault();setModal('openOrders')} }; window.addEventListener('keydown',key); return()=>window.removeEventListener('keydown',key) },[activeOrder.items.length,session])
  useEffect(()=>{ if(printSale){const t=setTimeout(()=>window.print(),100); return()=>clearTimeout(t)} },[printSale])
  const update = fn => setOrders(v=>v.map((o,i)=>i===active?fn(o):o)); const addProduct = p => { update(o=>({...o,items:[...o.items,{...p,price:p.unitPrice||p.price,lineId:`${p.id}-${Date.now()}`}]}));setModal(null) }
  const selectProduct = p => p.configurable?(setSelected(p),setModal('options')):addProduct({...p,quantity:1})
  const updateQuantity=(lineId,delta)=>update(o=>({...o,items:o.items.flatMap(i=>i.lineId===lineId?(i.quantity+delta<=0?[]:[{...i,quantity:i.quantity+delta}]):[i])}))
  const removeItem=lineId=>update(o=>({...o,items:o.items.filter(i=>i.lineId!==lineId)})); const chooseType=t=>{update(o=>({...o,orderType:t}));setModal(t==='داخل الكوفي'&&tablesEnabled?'tables':'payment')}; const chooseTable=t=>{update(o=>({...o,table:t}));setModal('payment')}
  const hold=()=>{if(!activeOrder.items.length)return;update(o=>({...o,held:true}));setModal('openOrders')}; const openOrder=id=>{const idx=orders.findIndex(o=>o.id===id);if(idx>=0){setActive(idx);setOrders(v=>v.map(o=>o.id===id?({...o,held:false}):o));setModal(null)}}
  const complete=payment=>{if(!session||!activeOrder.items.length)return;const originalItems=activeOrder.items.map(i=>({...i}));const sale={saleId:crypto.randomUUID(),id:crypto.randomUUID(),orderNumber:nextNumber,cashierId:session.cashierId,cashierNameSnapshot:session.cashierNameSnapshot,shiftId:session.shiftId,createdAt:Date.now(),subtotal,discount:activeOrder.discount?.value||0,total,paymentMethod:payment.method,payment,items:originalItems,order:{...activeOrder,items:originalItems}};setNextNumber(n=>n+1);setOrders(v=>v.map((o,i)=>i===active?({...blankOrder(o.id),name:o.name,completed:true,sale,lastSale:sale,originalItems,adjustments:o.adjustments||[]}):o));setSelected(sale);if(autoPrint)setPrintSale(sale);setModal(null)}
  const newOrder=()=>{const i=orders.findIndex(o=>!o.items.length&&!o.completed);if(i>=0){setActive(i);setModal(null)}else{setOrders(v=>[...v,blankOrder(v.length+1)]);setActive(orders.length);setModal(null)}}
  const applyDiscount=d=>{update(o=>({...o,discount:d}));setModal(null)}
  const recordAdjustment=a=>{const adjustment={...a,id:crypto.randomUUID(),type:'refund',time:Date.now(),originalSaleId:selected.sale?.id};setOrders(v=>v.map(o=>o.id===selected.id?({...o,adjustments:[...(o.adjustments||[]),adjustment]}):o));setModal('history');setSelected(v=>({...v,adjustments:[...(v.adjustments||[]),adjustment]}))}
  const addExisting=()=>{setModal('add-existing')}; const addToCompleted=p=>{const adjustment={id:crypto.randomUUID(),type:'add',product:p.name,quantity:p.quantity,amount:p.price,time:Date.now(),originalSaleId:selected.sale?.id};setOrders(v=>v.map(o=>o.id===selected.id?({...o,adjustments:[...(o.adjustments||[]),adjustment]}):o));setSelected(v=>({...v,adjustments:[...(v.adjustments||[]),adjustment]}));setModal('history')}
  const history=o=>{setSelected(o);setModal('history')}; const print=()=>setPrintSale(selected?.sale||selected); const onReceipt=s=>{setPrintSale(s);setModal(null)}; const login=cashier=>setSession({cashierId:cashier.cashierId,cashierNameSnapshot:cashier.name,shiftId:crypto.randomUUID(),openedAt:Date.now(),status:'open'}); const logout=()=>{setSession(null);setModal(null)}; const clearCart=()=>update(o=>({...o,items:[],discount:null,table:null,orderType:null,held:false}));
  return <main className="app-shell"><Header session={session} onOpenOrders={()=>setModal('openOrders')} onCashierMenu={()=>setModal('cashier-menu')}/><div className="quick-orders">{orders.slice(0,4).map((o,i)=><button onClick={()=>session&&setActive(i)} key={o.id} className={active===i?'active':''}><span>طلب {o.id}</span>{o.table&&<small>طاولة {o.table}</small>}{o.items.length>0&&<i>{o.items.reduce((s,x)=>s+x.quantity,0)}</i>}</button>)}<button className="quick-add" onClick={()=>session&&newOrder()} aria-label="فتح مساحة طلب جديدة"><Icon name="plus" size={18}/></button></div><div className="pos-layout"><ProductGrid products={visibleProducts} category={category} setCategory={setCategory} categories={categories} query={query} setQuery={setQuery} onSelect={session?selectProduct:()=>setModal('login')}/><OrderPanel order={activeOrder} updateQuantity={updateQuantity} removeItem={removeItem} onEdit={i=>(setSelected(i),setModal('options'))} onContinue={()=>setModal('orderType')} onHold={hold} onDiscount={()=>setModal('discount')} onClear={()=>setModal('confirm-clear')} onPrintMenu={()=>setModal('print-menu')} onReturn={()=>setModal('openOrders')} disabled={!session}/></div>
    {!session&&<div className="login-gate"><b>سجّل دخول الكاشير للبدء</b><button className="primary-action" onClick={()=>setModal('login')}>دخول الكاشير</button></div>}
    {modal==='login'&&<CashierLogin cashiers={mockCashiers} onClose={()=>setModal(null)} onLogin={login}/>} {modal==='cashier-menu'&&<CashierMenu session={session} onClose={()=>setModal(null)} onLogout={logout}/>} {modal==='confirm-clear'&&<ConfirmDialog title="إلغاء الطلب وإفراغ السلة؟" message="سيتم مسح الطلب الحالي فقط، ولن تتأثر الطلبات الأخرى." onClose={()=>setModal(null)} onConfirm={()=>{clearCart();setModal(null)}}/>} {modal==='print-menu'&&<PrintMenu enabled={autoPrint} onClose={()=>setModal(null)} onChange={v=>{setAutoPrint(v);setModal(null)}}/>}
    {modal==='options'&&<ProductOptions product={selected} onClose={()=>setModal(null)} onAdd={addProduct}/>} {modal==='orderType'&&<OrderType onClose={()=>setModal(null)} onChoose={chooseType}/>} {modal==='tables'&&<TableSelection orders={orders} onClose={()=>setModal(null)} onChoose={chooseTable}/>} {modal==='payment'&&<Payment total={total} onClose={()=>setModal(null)} onSuccess={complete}/>} {modal==='payment-electronic'&&<Payment initialMethod="إلكتروني" total={total} onClose={()=>setModal(null)} onSuccess={complete}/>} {modal==='quickCash'&&<QuickCash total={total} onClose={()=>setModal(null)} onSuccess={complete}/>} {modal==='discount'&&<DiscountDialog subtotal={subtotal} current={activeOrder.discount} onClose={()=>setModal(null)} onApply={applyDiscount}/>} {modal==='openOrders'&&<OpenOrders orders={orders} onClose={()=>setModal(null)} onSelect={openOrder} onHistory={history}/>} {modal==='history'&&<History order={selected} onClose={()=>setModal(null)} onReturn={()=>setModal('return')} onAdd={addExisting} onPrint={print} onReprint={print}/>} {modal==='return'&&<ReturnDialog order={selected} onClose={()=>setModal('history')} onConfirm={recordAdjustment}/>} {modal==='add-existing'&&<div className="overlay"><div className="dialog add-existing-dialog"><button className="close" onClick={()=>setModal('history')}><Icon name="x"/></button><h2>إضافة منتج إلى الطلب المكتمل</h2><ProductGrid products={products.filter(p=>!p.unavailable)} category="الكل" setCategory={()=>{}} categories={[]} query="" setQuery={()=>{}} onSelect={p=>addToCompleted({...p,quantity:1})}/></div></div>} {printSale&&<Receipt sale={printSale}/>}</main>
}
